[project]
name = "ohcrn-lei"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jochen Weile", email = "jweile@oicr.on.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
]

[project.scripts]
ohcrn-lei = "ohcrn_lei:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
